import type { Metadata } from "next";
import { Geist_Mono, Instrument_Sans } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'


const LT_Superior = localFont({
  src: [
    {
      path: './fonts/LTSuperiorSerif-Regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: "--font-lt-superior"
})


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const InstrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Gsap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${LT_Superior.variable} ${InstrumentSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
